### ISSUE TITLE
easyoop

### ISSUE THREAD

**Issue by barmalei** [fresheneesz/proto#3]
Suggest to take a look as the easyoop that is used in zebra project. It supports many OOP features like method overloading, overriding, access to parent class context, constructors, static fields, allows developers to create anonymous classes, etc.

https://github.com/barmalei/zebra

**Comment by fresheneesz** [comment]
Thanks for the note, but I'd really recommend you use a modular approach instead of bundling together a bunch of unrelated functionality into a big framework. Here's some background: https://www.pandastrike.com/posts/20150311-react-bad-idea
